package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Light Colors
val LightPrimary = Color(0xFF535F8A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD1E4FF)
val LightOnPrimaryContainer = Color(0xFF001D36)
val LightSecondary = Color(0xFF585E72)
val LightOnSecondary = Color(0xFF1A1C1E)
val LightSecondaryContainer = Color(0xFFE1E2EC)
val LightOnSecondaryContainer = Color(0xFF1A1C1E)
val LightBackground = Color(0xFFF7F9FF)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFE1E2EC)
val LightOnSurfaceVariant = Color(0xFF44474E)
val LightOutline = Color(0xFFE1E2EC)

// Error / Alert Colors (Accent colors from the theme)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

// Enabled / Success Colors (Natural green theme)
val SuccessPrimary = Color(0xFF2E7D32)
val SuccessOnPrimary = Color(0xFFFFFFFF)
val SuccessContainer = Color(0xFFE8F5E9)
val SuccessOnContainer = Color(0xFF0B2F10)
val SuccessOutline = Color(0xFFC8E6C9)

// Dark Colors (Complementary Dark Scheme under same palette theme)
val DarkPrimary = Color(0xFFBAC3FF)
val DarkOnPrimary = Color(0xFF242F58)
val DarkPrimaryContainer = Color(0xFF3B4770)
val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
val DarkSecondary = Color(0xFFC0C6DC)
val DarkOnSecondary = Color(0xFF2A3042)
val DarkBackground = Color(0xFF111318)
val DarkOnBackground = Color(0xFFE1E2EC)
val DarkSurface = Color(0xFF1A1C1E)
val DarkOnSurface = Color(0xFFE1E2EC)
val DarkOutline = Color(0xFF44474E)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
